language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-oscarescuderoarn
  api_key: cU5/LO4K46I88wEhNE2xgUWAL3iNNK0kcuv+a7WZd6ADqWFt888W5wKgSfsA86Qh1sO1URNmVlwOKqj+cjPktVXKj/CWO5jpQW0stFlioCrFVFvyZgPQq/shFZR7z86qe5Cwt/ekIuAcuOk+CqxxrwjLi1dTGtwBwkM0yHGomG60GqoBbyRHIdgB2uaoHTiIEM+VXQ/rS0DVtbkzq8h+Iw90Cg6XJP9ujCfES9aPuMpzyLI3OXw7oT7XIPWmUzQ7HBkfRJ62mNvDBLehryxpWsffBSGuQpY/0lseGYYwSasreAww5giu4+IWmj1eyE722rMAUyRnOtLrFMgJzquyZjZyp7z2f6bCx2g5kCRLzneieMPbNOEGWFcJjNtJJJcLIPXnO9zZBB21BnX7Wdw2nlezvwzP2npGqjaBQdKxeLI6mcFm3nrIvRhb4QadXOmm51eX0XCIKm8HHFdUTk9lq5GTpfen7lLJomIt4TRl24o81rxiJiXJlBwaLz8SepwI1dLoyLe+My7XBCrtf09JKZ2/+HnMNj0p7mhMkcytTXgoNnnGZ20obn9T5ZJiBPrmnIPOw/U6BRrV7nfYRAaosN9uT+JQ/e0iy4GbLT+CZOEZG5QDhuep3+AzGoGj244uxpXDwTbGkG4LQit7GvtPF47pxjGvMV7leMwDkEPLfqI=
